#spring:
#  datasource:
#    jdbc-url: jdbc:mysql://10.2.72.201:3306/tag_demo?useUnicode=true&characterEncoding=utf-8
#    driver-class-name: com.mysql.jdbc.Driver
#    username: bdp
#    password: bdp
spring:
  datasource:
    jdbc-url: jdbc:mysql://127.0.0.1:3306/urule_test?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

urule:
  repository:
    databasetype: mysql
    datasourcename: datasource

server:
  port: 8787
